### ISSUE TITLE
`...` notation in webpack config

### ISSUE THREAD

**Issue by robobenklein** [usulix/chrome-extension-webpack-boilerplate#1]
Not too sure why this fails for me:

```
> node utils/webserver.js

/home/robo/code/Grapplr/webpack.config.js:87
          ...JSON.parse(content.toString())
          ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/robo/code/Grapplr/utils/webserver.js:3:14)
```

But changing that section to:

```
new CopyWebpackPlugin([{
      from: "src/manifest.json",
      transform: function (content, path) {
        // generates the manifest file using the package.json informations
        manifest = JSON.parse(content.toString())
        manifest.description = process.env.npm_package_description
        manifest.version = process.env.npm_package_version
        return Buffer.from(JSON.stringify(manifest))
      }
    }]),
```
seems to have worked.

Any idea why it can't spread the dictionary here?

**Comment by usulix** [comment]
@robobenklein 

It took me a while to run into a similar issue in another project. I am guessing it is a node version issue.

I encountered it like this : https://github.com/nuxt/nuxt.js/issues/2927

and resolved it by upgrading node.

**Comment by robobenklein** [comment]
Indeed node was out of date. (Still was on 6.x >.< )
